### ISSUE TITLE
 net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: a

### ISSUE THREAD

**Issue by rubby-c** [FabricMC/fabric-example-mod#151] opened 2021-12-16 12:54 UTC
The latest version of fabric-example-mod, unedited, gives this strange exception without any proper error message or anything, just "a".

IDE: Intellij IDEA 2021.3 (the latest version)

Full stacktrace:
```
[14:49:05] [main/INFO] (FabricLoader/GameProvider) Loading Minecraft 1.18.1 with Fabric Loader 0.12.12
[14:49:05] [main/INFO] (FabricLoader) Loading 51 mods:
	- fabric 0.44.0+1.18
	- fabric-api-base 0.4.1+b4f4f6cdc8
	- fabric-api-lookup-api-v1 1.4.0+16d92c47c8
	- fabric-biome-api-v1 6.0.1+ded849a9c8
	- fabric-blockrenderlayer-v1 1.1.9+3ac43d95c8
	- fabric-command-api-v1 1.1.6+3ac43d95c8
	- fabric-commands-v0 0.2.5+b4f4f6cdc8
	- fabric-containers-v0 0.1.18+d154e2c6c8
	- fabric-content-registries-v0 0.4.5+6f53a73dc8
	- fabric-crash-report-info-v1 0.1.8+3ac43d95c8
	- fabric-data-generation-api-v1 1.0.0+3fec4ad9c8
	- fabric-dimensions-v1 2.1.7+43d29571c8
	- fabric-entity-events-v1 1.4.5+6b21378ac8
	- fabric-events-interaction-v0 0.4.16+bfa23f17c8
	- fabric-events-lifecycle-v0 0.2.6+b4f4f6cdc8
	- fabric-game-rule-api-v1 1.0.10+3ac43d95c8
	- fabric-gametest-api-v1 1.0.5+03d159cfc8
	- fabric-item-api-v1 1.3.0+691a79b5c8
	- fabric-item-groups-v0 0.3.3+3ac43d95c8
	- fabric-key-binding-api-v1 1.0.8+c8aba2f3c8
	- fabric-keybindings-v0 0.2.6+b4f4f6cdc8
	- fabric-lifecycle-events-v1 1.4.10+c15ca335c8
	- fabric-loot-tables-v1 1.0.8+3ac43d95c8
	- fabric-mining-level-api-v1 1.0.3+3ac43d95c8
	- fabric-mining-levels-v0 0.1.7+b4f4f6cdc8
	- fabric-models-v0 0.3.3+3ac43d95c8
	- fabric-networking-api-v1 1.0.18+3ac43d95c8
	- fabric-networking-v0 0.3.5+b4f4f6cdc8
	- fabric-object-builder-api-v1 1.11.0+3b82842ec8
	- fabric-object-builders-v0 0.7.8+3ac43d95c8
	- fabric-particles-v1 0.2.9+526dc1acc8
	- fabric-registry-sync-v0 0.8.5+3ac43d95c8
	- fabric-renderer-api-v1 0.4.9+3ac43d95c8
	- fabric-renderer-indigo 0.4.12+3ac43d95c8
	- fabric-renderer-registries-v1 3.2.7+b4f4f6cdc8
	- fabric-rendering-data-attachment-v1 0.3.4+7242e9d7c8
	- fabric-rendering-fluids-v1 0.1.18+3ac43d95c8
	- fabric-rendering-v0 1.1.9+b4f4f6cdc8
	- fabric-rendering-v1 1.10.3+6b21378ac8
	- fabric-resource-loader-v0 0.4.11+3ac43d95c8
	- fabric-screen-api-v1 1.0.7+3ac43d95c8
	- fabric-screen-handler-api-v1 1.1.11+3ac43d95c8
	- fabric-structure-api-v1 2.0.8+295197a7c8
	- fabric-tag-extensions-v0 1.2.5+3ac43d95c8
	- fabric-textures-v0 1.0.9+3ac43d95c8
	- fabric-tool-attribute-api-v1 1.3.4+7de09f55c8
	- fabric-transfer-api-v1 1.5.5+b4f4f6cdc8
	- fabricloader 0.12.12
	- java 17
	- minecraft 1.18.1
	- modid 1.0.0
[14:49:05] [main/INFO] (FabricLoader/Mixin) SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/C:/Users/rubby/.gradle/caches/modules-2/files-2.1/net.fabricmc/sponge-mixin/0.10.7+mixin.0.8.4/7a4ca9d54d9ae564dea0363d668036a8420ed9b8/sponge-mixin-0.10.7+mixin.0.8.4.jar Service=Knot/Fabric Env=CLIENT
[14:49:06] [main/INFO] (FabricLoader/Mixin) Loaded Fabric development mappings for mixin remapper!
[14:49:06] [main/INFO] (FabricLoader/Mixin) Compatibility level set to JAVA_16
[14:49:12] [main/WARN] (FabricLoader/Mixin) @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$zgj000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[14:49:12] [main/ERROR] (FabricLoader) Minecraft has crashed!
 net.fabricmc.loader.impl.FormattedException: java.lang.NoSuchFieldError: a
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:610) ~[fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.12.12.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
Caused by: java.lang.NoSuchFieldError: a
	at net.minecraft.util.dynamic.Codecs$Lazy.toString(Codecs.java:348) ~[minecraft-project-@-mapped.jar:?]
	at com.mojang.serialization.Codec.lambda$fieldOf$1(Codec.java:175) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$1.toString(MapCodec.java:44) ~[datafixerupper-4.0.26.jar:?]
	at java.lang.String.valueOf(String.java:4215) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:169) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$Instance$5.toString(RecordCodecBuilder.java:341) ~[datafixerupper-4.0.26.jar:?]
	at java.lang.String.valueOf(String.java:4215) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:169) ~[?:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder$2.toString(RecordCodecBuilder.java:122) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.MapCodec$MapCodecCodec.toString(MapCodec.java:101) ~[datafixerupper-4.0.26.jar:?]
	at java.lang.String.valueOf(String.java:4215) ~[?:?]
	at java.lang.StringBuilder.append(StringBuilder.java:169) ~[?:?]
	at com.mojang.serialization.codecs.ListCodec.toString(ListCodec.java:82) ~[datafixerupper-4.0.26.jar:?]
	at com.mojang.serialization.Codec.flatXmap(Codec.java:167) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.util.dynamic.Codecs.nonEmptyList(Codecs.java:307) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.util.math.Spline.method_39233(Spline.java:115) ~[minecraft-project-@-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.util.math.Spline.method_39232(Spline.java:113) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.world.biome.source.util.VanillaTerrainParameters.<clinit>(VanillaTerrainParameters.java:28) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.world.gen.chunk.GenerationShapeConfig.method_28582(GenerationShapeConfig.java:41) ~[minecraft-project-@-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.chunk.GenerationShapeConfig.<clinit>(GenerationShapeConfig.java:31) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGeneratorSettings.method_28558(ChunkGeneratorSettings.java:27) ~[minecraft-project-@-mapped.jar:?]
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-4.0.26.jar:?]
	at net.minecraft.world.gen.chunk.ChunkGeneratorSettings.<clinit>(ChunkGeneratorSettings.java:26) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.util.registry.BuiltinRegistries.method_30566(BuiltinRegistries.java:78) ~[minecraft-project-@-mapped.jar:?]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721) ~[?:?]
	at net.minecraft.util.registry.BuiltinRegistries.<clinit>(BuiltinRegistries.java:77) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.util.registry.Registry.<clinit>(Registry.java:269) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.Bootstrap.initialize(Bootstrap.java:49) ~[minecraft-project-@-mapped.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:155) ~[minecraft-project-@-mapped.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608) ~[fabric-loader-0.12.12.jar:?]
	... 3 more

Process finished with exit code 1

```

**Comment by Andrews54757** [comment] 2021-12-20 05:19
same.

**Comment by haykam821** [comment] 2021-12-20 05:21
This is likely a duplicate of FabricMC/fabric#1903. See https://github.com/FabricMC/fabric/discussions/1903#discussioncomment-1798128 for a solution.

**Closed** 2022-01-16 19:38 UTC
