### ISSUE TITLE
Any IDE error on gradle download

### ISSUE THREAD

**Issue by EleC0TroN** [FabricMC/fabric-example-mod#29] opened 2019-08-25 14:40 UTC
Could not unzip C:\Users\samsung\.gradle\wrapper\dists\gradle-5.5.1-bin\cfsov38hb3r1zj4ic9bbjcc7n\gradle-5.5.1-bin.zip to C:\Users\samsung\.gradle\wrapper\dists\gradle-5.5.1-bin\cfsov38hb3r1zj4ic9bbjcc7n.
Reason: error in opening zip file
Exception in thread "main" java.util.zip.ZipException: error in opening zip file
        at java.util.zip.ZipFile.open(Native Method)
        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
        at java.util.zip.ZipFile.<init>(ZipFile.java:169)
        at org.gradle.wrapper.Install.unzip(Install.java:219)
        at org.gradle.wrapper.Install.access$600(Install.java:27)
        at org.gradle.wrapper.Install$1.call(Install.java:75)
        at org.gradle.wrapper.Install$1.call(Install.java:48)
        at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
        at org.gradle.wrapper.Install.createDist(Install.java:48)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:63)

**Comment by EleC0TroN** [comment] 2019-08-25 14:45
Could not install Gradle distribution from 'https://services.gradle.org/distributions/gradle-5.5.1-bin.zip'.
error in opening zip file

**Comment by modmuss50** [comment] 2019-08-25 21:12
Seems like the file failed to download, try deleting the .gradle folder and trying again. Closing this as its not a bug. If you require further help ask in the discord or possibly search online for the same error as its not a fabric error.

**Closed by modmuss50** 2019-08-25 21:12 UTC
