### ISSUE TITLE
[Request] Include MC default folder structure

### ISSUE THREAD

**Issue by xanthian** [FabricMC/fabric-example-mod#204] opened 2022-08-14 19:21 UTC
Assets
> modid >
>> blockstates
>> lang
>> models>
>>> block
>>> item
>> textures >
>>> block
>>> item

Data
> modid >
>> loot_tables
>> recipes
>> tags >
>>> item
>>> block

These form the basis for the majority of mods and would save me ~5 minutes creating these each time :)

**Comment by Juuxel** [comment] 2022-08-14 19:32
Duplicate of #203.

**Closed by Juuxel** 2022-08-14 19:32 UTC
Labels: duplicate

**Comment by xanthian** [comment] 2022-08-14 19:35
sorry, browser went wonky :)
